In [44]:
import os
from models.llama.tokenizer import Tokenizer # Assumes tokenizer.py is in the same directory orPYTHONPATH
os.environ["TIKTOKEN_CACHE_DIR"] = "" # Add this line




In [68]:
dummy_model_filename = "dummy_custom_model.tiktoken"

    # A BPE ranks file where tokens align with pat_str behavior.
    # "token"   -> dG9rZW4=
    # "1"       -> MQ==
    # "2"       -> Mg==
    # " "       -> IA==
    # "b"       -> Yg==
    # "c"       -> Yw==
    # "a"       -> YQ== 
    # "e"       -> ZQ==
    # "o"       -> bw==
    # "t"       -> dA==
    # "i"       -> aQ==
    # "d"       -> ZA==
    # "eo"      -> ZW8=
    # "ot"      -> b3Q=
    # "eot"     -> ZW90
    # "<"       -> PA==
    # "|"       -> fA==
    # "_"       -> Xw==
    # "id"      -> aWQ=
    # ">"       -> Pg==
dummy_model_content= """
dG9rZW4= 0
MQ== 1
Mg== 2
IA== 3
Yg== 4
Yw== 5
YQ== 6
ZQ== 7
bw== 8
dA== 9
aQ== 10
ZA== 11
ZW8= 12
b3Q= 13
ZW90 14
PA== 15
fA== 16
Xw== 17
aWQ= 18
Pg== 19
"""""

In [69]:
processed_content = dummy_model_content.strip()

with open(dummy_model_filename, "w", encoding="utf-8") as f:
    f.write(processed_content)
print(f"Created dummy tokenizer model: {dummy_model_filename}")


Created dummy tokenizer model: dummy_custom_model.tiktoken


In [70]:

# 2. Initialize the Tokenizer
# Note: The Tokenizer class defines its own special tokens like <|eot_id|>,
# which will be added on top of the base vocabulary from the dummy file.
print("\nInitializing tokenizer with dummy model...")
tokenizer = Tokenizer(model_path=dummy_model_filename)
print("Tokenizer initialized successfully.")





        


Initializing tokenizer with dummy model...
{b'token': 0, b'1': 1, b'2': 2, b' ': 3, b'b': 4, b'c': 5, b'a': 6, b'e': 7, b'o': 8, b't': 9, b'i': 10, b'd': 11, b'eo': 12, b'ot': 13, b'eot': 14, b'<': 15, b'|': 16, b'_': 17, b'id': 18, b'>': 19}
Tokenizer initialized successfully.


In [71]:
import base64

In [61]:
print(base64.b64encode(b"d"))

b'ZA=='


In [72]:
special_token_str = "<|eot_id|>"

In [73]:
expected_tokens_for_disallowed_special = [13, 14, 12, 15, 16, 17]
actual_tokens = tokenizer.encode(special_token_str, bos=False, eos=False, allowed_special=set())

In [74]:
actual_tokens

[15, 16, 14, 17, 18, 16, 19]

In [1]:
import jax
import jax.numpy as jnp

key = jax.random.PRNGKey(0)
arr = jax.random.randint(key, (10,5), 0, 30)

print(arr)

[[19  0  2 13 11]
 [27 12 23  3  3]
 [16 24 10  9 29]
 [25 28  0 12 21]
 [23  6 12 25  7]
 [15 18 25 18 18]
 [19 14 29  7 23]
 [14  7  8  9 28]
 [16 27  2  3 21]
 [24 13  8 18 23]]


In [6]:
import jax
import jax.numpy as jnp

arr = jnp.zeros((2,3),dtype="float32")
brr = arr.astype("float32")
print(brr.dtype)

float32


In [9]:
sorted_indices

Array([[0, 3, 4, 2, 1],
       [0, 2, 1, 4, 3],
       [4, 1, 0, 2, 3],
       [1, 0, 4, 3, 2],
       [3, 0, 2, 4, 1],
       [2, 4, 3, 1, 0],
       [2, 4, 0, 1, 3],
       [4, 0, 3, 2, 1],
       [1, 4, 0, 3, 2],
       [0, 4, 3, 1, 2]], dtype=int32)

In [13]:
arr[sorted_indices][0][1]

Array([25, 28,  0, 12, 21], dtype=int32)

: 